name: hive_multiisolate
description: A class allowing the user of Hive across isolates.
homepage: https://github.com/TheCarpetMerchant/hive_multiisolate
version: 1.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hive: ^2.0.0

dev_dependencies:
  lints: ^2.0.0